### PR TITLE
api: add deprecatedversion marker

### PR DESCRIPTION
**Pull request by shunki-fujita**
add deprecatedversion marker.
Part of https://github.com/cybozu-go/moco/issues/545

### CODE REVIEW

**Review by ymmt2005 — COMMENTED** [review]
Question.
I know the `warning` is optional, but what happens if we don't give it?

**Comment by shunki-fujita** [comment]
@ymmt2005 
> Question. I know the `warning` is optional, but what happens if we don't give it?

Probably use the following format:
https://github.com/kubernetes/kubernetes/blob/558a6797a2962dd77c38345549d2a2452bbc3cdc/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go#L1037

**Comment by ymmt2005** [comment]
Thanks.

**Review by ymmt2005 — APPROVED** [review]
LGTM

**Pull request merged**
