### PR TITLE
Prevent disabling of binlog

### PR DESCRIPTION
**Pull request by d-kuro**
refs: https://github.com/cybozu-go/moco/issues/638

### CODE REVIEW

**Review by ymmt2005 — APPROVED** [review]
LGTM. Thank you.

**Comment by vsliouniaev** [comment]
I'm currently using the operator with single DB instances and explicitly disabling binary logging as I don't need replication but a very lightweight implementation.

Is it possible to maintain this behavior?

**Comment by ymmt2005** [comment]
I'm afraid not.
Even a single cluster needs binlogs for MOCO because we allow users to add replicas later, which needs binlogs.

**Comment by vsliouniaev** [comment]
What if there was a CRD level option that would allow for this, provided that the number of replicas is 1? That would be easier to validate.

**Comment by ymmt2005** [comment]
@masa213f @d-kuro thoughts?

**Comment by d-kuro** [comment]
@vsliouniaev @ymmt2005 
Can `_includ` be used?
https://cybozu-go.github.io/moco/usage.html?highlight=_inc#opaque-configuration

**Comment by ymmt2005** [comment]
yup, that should work.

**Comment by vsliouniaev** [comment]
Thanks that's very helpful!

**Pull request merged**
