### PR TITLE
Allow users to customize containers resources

### PR DESCRIPTION
**Pull request by d-kuro**
refs: https://github.com/cybozu-go/moco/issues/235

Implemented based on proposals added at https://github.com/cybozu-go/moco/pull/394

### CODE REVIEW

**Review by ymmt2005 — COMMENTED** [review]
Looks good, but I want to add the default limits (== requests) for these containers
so that users would not necessarily specify the resource limits/requests.

**Comment by masa213f** [comment]
@d-kuro 
Sorry to add extra work. Could you also set default values?
I checked the resource usage in our cluster. And I decided on the default values as follows.
Please see this comment too: https://github.com/cybozu-go/moco/issues/235#issuecomment-1022947850

| container | max memory usage | max cpu usage | default memory requests/limits | default memory requests/limits |
| --- | --- | --- | --- | --- |
| agent | 65MB | 7ms | 100MB | 100ms |
| slow-log | 10MB | 0.4ms | 20MB | 100ms |
| mysqld-exporter | 47MB |  20ms | 100MB | 200ms |
| moco-init | 63MB |  ??? | 100MB | 100ms |

**Comment by masa213f** [comment]
Max memory usage:
memory

Max CPU usage:
cpu

**Comment by zoetrope** [comment]
Sorry, #397 caused the conflict.
Please rebase and regenerate the CRD manifest.

**Comment by d-kuro** [comment]
@ymmt2005 @masa213f 
Thanks! I added default container resource definitions.
https://github.com/cybozu-go/moco/pull/395/commits/a7093f9f8caa05481e30baa64cb6d35776f7772e

and, Added a commit to tune up the default resource definition, which caused E2E to fail due to lack of resources.
https://github.com/cybozu-go/moco/pull/395/commits/4983f5425f6d6dddbca785ea3e67ae4bfa69cc24

**Review by ymmt2005 — APPROVED** [review]
LGTM

**Review by masa213f — APPROVED** [review]
LGTM

**Comment by zedtux** [comment]
When will you update the Helm chart please ?

**Comment by d-kuro** [comment]
@zedtux 
cc: @masa213f @zoetrope 

A GitHub release with these changes has not yet been created.
Please wait for the Helm chart to be upgraded as soon as a release is made 🙏

**Pull request merged**
